-- Création de la table 'services'
create table services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  image text,
  gradient text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Création de la table 'projects' (Portfolio)
create table projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  tag text,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Activation de la sécurité (RLS)
alter table services enable row level security;
alter table projects enable row level security;

-- Création d'une politique pour permettre la lecture publique (tout le monde peut voir)
create policy "Public services are viewable by everyone"
  on services for select
  using ( true );

create policy "Public projects are viewable by everyone"
  on projects for select
  using ( true );

-- Création d'une politique pour permettre l'écriture uniquement aux utilisateurs connectés (Admin)
create policy "Users can insert services"
  on services for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update services"
  on services for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete services"
  on services for delete
  using ( auth.role() = 'authenticated' );

create policy "Users can insert projects"
  on projects for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update projects"
  on projects for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete projects"
  on projects for delete
  using ( auth.role() = 'authenticated' );
