-- Create pricing_plans table
CREATE TABLE IF NOT EXISTS pricing_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price TEXT NOT NULL,
    currency TEXT DEFAULT '€',
    features TEXT[] DEFAULT '{}',
    is_popular BOOLEAN DEFAULT false,
    category TEXT NOT NULL,
    button_text TEXT DEFAULT 'Commander',
    button_link TEXT DEFAULT '/contact',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE pricing_plans ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public read access" ON pricing_plans
    FOR SELECT USING (true);

CREATE POLICY "Allow authenticated insert" ON pricing_plans
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated update" ON pricing_plans
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated delete" ON pricing_plans
    FOR DELETE USING (auth.role() = 'authenticated');

-- Seed initial data
INSERT INTO pricing_plans (title, price, features, is_popular, category, button_text) VALUES
(
    'Site Vitrine',
    '899',
    ARRAY[
        'Design personnalisé et sur mesure',
        'Optimisation SEO de base',
        'Certificat de sécurité HTTPS',
        'Responsive (Mobile & Tablette)',
        'Formulaire de contact',
        'Performance optimisée',
        'Jusqu''à 5 pages'
    ],
    false,
    'Développement Web',
    'Commander'
),
(
    'Site E-Commerce',
    '1499',
    ARRAY[
        'Boutique en ligne complète',
        'Design personnalisé',
        'Gestion des produits & stocks',
        'Paiement sécurisé (Stripe/PayPal)',
        'Panel administration',
        'Optimisation SEO avancée',
        'Formation prise en main'
    ],
    true,
    'Développement Web',
    'Démarrer'
),
(
    'Tunnel de Vente',
    '699',
    ARRAY[
        'Page de vente haute conversion',
        'Copywriting persuasif',
        'Design épuré et ciblé',
        'Intégration Email Marketing',
        'A/B Testing',
        'Responsive Design',
        'Appel à l''action optimisé'
    ],
    false,
    'Développement Web',
    'Lancer'
);
